server:
  port: 5000
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:h2:mem:spring_boot_api
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: always
