server:
  port: 5000
  error:
    include-stacktrace: never
spring:
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  exchange:
    direct: direct
    fanout: fanout
    topic: topic
  queue:
    queue01: queue01
    queue02: queue02
  routing-key:
    orange: orange
    black: black
    green: green