version: '3.9'

services:

  rabbitmq:
    container_name: rabbitmq
    network_mode: bridge
    image: rabbitmq:3.13.0-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672