version: '3.9'

services:

  mysql8.0:
    network_mode: bridge
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 5001:3306
  
  redis-7.2.1-alpine:
    network_mode: bridge
    image: redis:7.2.1-alpine
    restart: unless-stopped
    volumes:
      - ./docker/redis/data:/data
    ports:
      - 6379:6379