version: '3.9'
services:
  database:
    container_name: docker-project-mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_boot_api
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 5001
    ports:
      - 5001:5001
    networks:
      - docker-project-network
  spring-boot-api:
    container_name: docker-project-spring-boot-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://database:5001/spring_boot_api?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 5000:5000
    command: mvn spring-boot:run
    depends_on:
      - database
    networks:
      - docker-project-network
networks:
  docker-project-network:
    name: docker-project-network
    driver: bridge