version: '3.9'
services:
  database:
    container_name: mysql
    network_mode: bridge
    image: mysql:8.0
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #   - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - 5001:3306