# server
server:
  port: 5000
  error:
    include-stacktrace: never
spring:
  # database
  datasource:
    url: jdbc:mysql://localhost:5001/spring_boot_api?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa
  jpa:
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false
    hibernate:
      ddl-auto: none
  # console output
  output:
    ansi:
      enabled: always
