-- Dummy data generated by https://generatedata.com/generator

INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Porter','Briggs',70,'in.faucibus@protonmail.couk',0);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Guy','Hernandez',60,'justo.sit@aol.com',1);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Kaitlin','Calderon',62,'lorem.semper@google.org',0);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Lionel','Barnett',76,'placerat.eget@outlook.org',0);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Samson','Fulton',80,'enim.etiam.gravida@aol.com',0);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Hadassah','Duncan',89,'arcu@protonmail.net',1);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Mohammad','Daniel',25,'nibh@yahoo.ca',0);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Quyn','Lawrence',38,'consectetuer.cursus@yahoo.org',0);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Maxwell','Pollard',60,'arcu.sed@google.com',0);
INSERT INTO USERS (first_name,last_name,age,email,is_active) VALUES ('Joel','Anderson',41,'sem.mollis@yahoo.net',1);